### ISSUE TITLE
Functionality - Individual Profile Page (InstancesTab)

### ISSUE THREAD

**Issue by Jinsuke** [HP-Corel/AttendanceTracker#32]
Site: http://16.178.42.203/users/profile?userid=1
--
Features
--
- Page to let Admins / Regular user to see their Lates/Instances/Sick Leaves.
- Admin access has the right to reset tardiness count on the Instances toggle.

Screenshot
--
![image](https://cloud.githubusercontent.com/assets/10201846/8450445/897ca9f0-200d-11e5-851b-5ef6a00fd8ed.png)

**Comment by asjr4584** [comment]
@alvincrisuycorel when can we implement the dashboard so that @Jinsuke can start computing the Instances record?

**Comment by asjr4584** [comment]
@Jinsuke @alvincrisuycorel I would like the functionality of the Excuse button be similar to Flexi time:

![sdfad](https://cloud.githubusercontent.com/assets/4827031/8590077/85395fe4-264f-11e5-9b3a-013ed3b10f0f.png)

**Comment by Jinsuke** [comment]
Update
-
- Slightly working functionalities [Login/Shortbreak/Longbreak/Status/Late in Minutes counting]

**To Follow:**
- Fix table information per day and per month 
- Fix Total Minutes of Late/No. of instances and Rest Tardiness Button
- Fix Absenteeism table

**NOTE: TABS HAS BEEN CHANGED. CALENDAR, ATTENDANCE AND INSTANCES TABS ARE NOW SEPARATE PAGES**

Screenshot
-
![image](https://cloud.githubusercontent.com/assets/10201846/8668704/7c29e32a-2a40-11e5-9c78-2e390a867e91.png)
![image](https://cloud.githubusercontent.com/assets/10201846/8668714/9400bcf8-2a40-11e5-8d46-eda08c2a048b.png)

**Comment by alvincrisuycorel** [comment]
For Testing

**Comment by asjr4584** [comment]
@gigiadamantopoulos for testing, please.

**Comment by Jinsuke** [comment]
:new: Update 150727
-
- Changed text for overall and total instances/late record.
- Added responsive tables instead of div
![image](https://cloud.githubusercontent.com/assets/10201846/8896907/d075effe-343c-11e5-853a-40a3866f1d10.png)

Hi @gigiadamantopoulos ,
Are there still any functions in this page that doesn't work? I was wondering why I assigned this case to my name last Friday. If possible, can you please check and test the functionality? Thank you! :grin:

**Comment by gigiadamantopoulos** [comment]
I didn't find any error as of now... although I have a question:

Is it possible that we add an hour conversion if it exceeds 60 mins?

![image](https://cloud.githubusercontent.com/assets/10202106/8990027/51abf220-3722-11e5-9312-be2d5b3cd9fc.png)

**Comment by alvincrisuycorel** [comment]
Hi Ma'am Evs,

Possible po :smile:

**Comment by alvincrisuycorel** [comment]
Done. Please check po :smile:

**Comment by gigiadamantopoulos** [comment]
Passed, although we must find a way to auto-refresh the page so that the instances will be updated.

**Comment by lyn2711** [comment]
Can we change "Total # of Late" to "Total mins late".  And I think it should be shown in minutes even if it is over 60 minutes.

![image](https://cloud.githubusercontent.com/assets/7370325/9274326/60642a2a-42c7-11e5-902f-9d736b50694e.png)

**Comment by gigiadamantopoulos** [comment]
passed in 201

**Comment by gigiadamantopoulos** [comment]
Hi @alvincrisuycorel ,

Additional issue on this one, when the TL checked the reset tardiness account, the Supervisor did not receive any notification as well and the checkbox is not clickable...

Can you please double check?

**Comment by asjr4584** [comment]
OVERDUE

**Comment by alvincrisuycorel** [comment]
Hi Gigi could you check this issue if this also exist in 203?

**Comment by asjr4584** [comment]
Hi Team,

Can you we prioritize this, please?

**Comment by alvincrisuycorel** [comment]
Hi sir ok po.

Deadline September 14, 2015

**Comment by asjr4584** [comment]
I see, Thanks @gigiadamantopoulos ,

@Alvin, can you add this feature by September 14, too? We must find a way to auto-refresh the page so that the instances will be updated.

**Comment by alvincrisuycorel** [comment]
Noted sir

**Comment by alvincrisuycorel** [comment]
Added
- Notification for Supervisor when TL check the checkbox in instance page
- Notification for TL when Supervisor check the checkbox in instance page
- Notification for TL when Supervisor click the button of reset tardy count
- Notification for TL when Supervisor click the button of reset instance
- Notification for TL when an Agent occur an instance when a TL or a Supervisor access the instance page of that Agent have an instance
- No need to refresh instance page to show instances of the Agent

Hi Gigi kindly check the ff. if these are correct in 203

**Comment by gigiadamantopoulos** [comment]
Hi @alvincrisuycorel , as discussed, there are still issues

**Comment by alvincrisuycorel** [comment]
Hi Gigi could you test it again?

@gigiadamantopoulos

**Comment by gigiadamantopoulos** [comment]
Hi Alvin, notification works already... although some minor errors:

When notification alerts:
![image](https://cloud.githubusercontent.com/assets/10202106/9870844/0deb4328-5bc2-11e5-90b6-ddaf1e557d2d.png)

When notifications are read:
![image](https://cloud.githubusercontent.com/assets/10202106/9870853/194736e6-5bc2-11e5-8071-d9fa351cd3f4.png)

Kindly arrange the messages according to the received time (similar to FB)

**Comment by alvincrisuycorel** [comment]
Hi Gigi @gigiadamantopoulos 

Kindly check this again po :smile:

**Comment by asjr4584** [comment]
@lyn2711 i'm assigning this to you now so you can test since Gigi is on VL today.

**Comment by asjr4584** [comment]
@lyn2711<https://github.com/lyn2711> i'm assigning this to you now so you can test since Gigi is on VL today.

**Comment by lyn2711** [comment]
Test done in 201.  Notifications are listed from oldest date to newest date as shown in screenshot:


![image](https://cloud.githubusercontent.com/assets/7370325/9896965/5df71f82-5c75-11e5-8483-eb4f06e30567.png)

**Comment by Jinsuke** [comment]
Issue
-
- PRESENT STATUS is tagged on Absenteeism Table on Instances Tab. Only Absent, SL, NCNS, EL, and JA should be tagged inside Absenteeism Table.

![image](https://cloud.githubusercontent.com/assets/10201846/9926777/f1402dbc-5d4a-11e5-8c4b-a5ab2aa6e9ec.png)

Done in my local pc. For Testing on local.
http://16.178.42.181/
-
**All Passwords are: 123**
- **Admin Account:** jin@gmail.com

- **Supervisor Account:** alvincris.uy@hpe.com

- **TL Account:**
  - Dev Team: alfredoa.salvadorjr@hp.com
  - Team Mark: marktristan.cruz@hpe.com

- **Agent Account:**
  - Dev Team:
    - christopher.perez@hpe.com
  - Team Mark:
    - reynan.fortes@hpe.com

**Comment by gigiadamantopoulos** [comment]
Passed... merged to 203... @alvincrisuycorel

**Comment by Jinsuke** [comment]
Issue
-
- Undertime Error. Even if Agent log in early and logs out exactly at four (by the auto logout feature). It will still list it as an Undertime record.

![image](https://cloud.githubusercontent.com/assets/10201846/9927160/b1581fee-5d4e-11e5-8a34-b00a026650d7.png)

**Comment by asjr4584** [comment]
Hi Jin,

I am still seeing “Present” status in the Absenteeism section.

This screen shot is from Gigi’s user profile:

Please advise.

[cid:image001.png@01D0F15E.FEB1CF30]

**Comment by Jinsuke** [comment]
Hi Sir,

The Present Statuses were already created by the system before we were able to push the new code. As discussed, database will be reset later. :)

**Comment by Jinsuke** [comment]
Update
-
- **ADDED** *fix for UNDERTIME Status*

![image](https://cloud.githubusercontent.com/assets/10201846/9949660/38d48eb0-5de2-11e5-987c-8a7ed94c97c3.png)

**Comment by asjr4584** [comment]
@gigiadamantopoulos please prioritize this overdue issue.

**Comment by gigiadamantopoulos** [comment]
As discussed with kuya @Jinsuke , this is not done.

**Comment by Jinsuke** [comment]
Update
-
Will transfer issue to @alvincrisuycorel as this is connected to the Dashboard revision.

**Comment by asjr4584** [comment]
@Jinsuke can we fix this today?

**Comment by gigiadamantopoulos** [comment]
As reported by Sir @asjr4584 

Hi Gigi,
I did change Chris’ Unauthorized Absences yesterday to SL but it still reflected in his instance as Unathorized Absence. Please see below:
 
![image](https://cloud.githubusercontent.com/assets/10202106/10091836/86702bda-6372-11e5-8f3d-7de153201aa1.png)

http://16.178.42.201/users/instances/35002199

**Comment by Jinsuke** [comment]
*Update: As per Alvin, this is already working on the revised Dashboard page*

**Comment by alvincrisuycorel** [comment]
Hi Gigi @gigiadamantopoulos 

Kindly check in 203 :smile:

**Comment by gigiadamantopoulos** [comment]
Passed in 203

**Comment by asjr4584** [comment]
@lyn2711 for testing in 201.

**Comment by Jinsuke** [comment]
Testing Production 201
-
- Results: OK! :+1: 
- Tried Changing Absent Status to SL and checked Instances and Dashboard Page.

![image](https://cloud.githubusercontent.com/assets/10201846/10210421/674e0dca-6819-11e5-864e-cf511d1b49e5.png)

**Comment by Jinsuke** [comment]
Update
-
- Fixed Instances Reset Function

![image](https://cloud.githubusercontent.com/assets/10201846/10238285/29901140-68f0-11e5-8575-e35a5818719b.png)

For testing on Local http://16.178.42.181/users/instances/35002194
-

**Comment by lyn2711** [comment]
Passed, test done in 181

**Comment by alvincrisuycorel** [comment]
Merged in 203

**Comment by Jinsuke** [comment]
Issue
-
- Issues found with Overall Instances Computation
- Dashboard 201 full of Undertime Status.

**Comment by alvincrisuycorel** [comment]
Hi kuya Jerome,

Regarding
- Dashboard 201 full of Undertime Status.

I have a fix for this issue that is already in #1 

Though we need to re'submit all the filed leaves if ever they already have because the status are already "Undertime". Before doing so we need to fix the issue of Edit button of the Event.

**Comment by Jinsuke** [comment]
For testing on Production 201 http://16.178.42.201/
-

**Comment by Jinsuke** [comment]
Please test again in 203 :grin: :

**Comment by gigiadamantopoulos** [comment]
Hi kuya @Jinsuke ,

I tested this in 201, I noticed that I was marked as Late on Oct 1 and 2 because I am on VL that day...
Also, the computation on total minutes late is the same in all instances, which is weird...

![image](https://cloud.githubusercontent.com/assets/10202106/10325594/628b4388-6cc5-11e5-893a-54617b3a01cb.png)

**Comment by alvincrisuycorel** [comment]
Hi Gigi, @gigiadamantopoulos 

Just fixed the issue. I think the data in 201 are not applicable.

Can you test it on 203?

**Comment by gigiadamantopoulos** [comment]
Hi kuya @Jinsuke , can you give me a copy of the software connected to the server so that i can proceed with the testing for this issue?

thanks

**Comment by Jinsuke** [comment]
Copy sent! :) For testing again.

**Comment by gigiadamantopoulos** [comment]
As of now, we have to wait for the times to be recorded since we can alter the time.

Suggestion: Can we hide the Instances tab for admin accounts since they don't need it

**Comment by Jinsuke** [comment]
Update
-
- Instances Page now only appears on Agent accounts.

**SUPERVISOR ACCOUNT**
![image](https://cloud.githubusercontent.com/assets/10201846/10475441/450e821e-7276-11e5-98ac-beadce1ee88c.png)

**AGENT ACCOUNT**
![image](https://cloud.githubusercontent.com/assets/10201846/10475442/4bfcb0c8-7276-11e5-8c34-3df04bde9862.png)

**Comment by gigiadamantopoulos** [comment]
hi kuya @Jinsuke, there is an existing issue with the instances tab in the Total Time Late section:
![image](https://cloud.githubusercontent.com/assets/10202106/10502102/011cb940-731b-11e5-928e-80ea49148ece.png)

and the Absenteesim section does not reflect the correct info:
![image](https://cloud.githubusercontent.com/assets/10202106/10502150/83766454-731b-11e5-8902-83f6aa77caea.png)

**Comment by alvincrisuycorel** [comment]
Hi Gigi, @gigiadamantopoulos 

Can you try creating a new org? :smile:

**Comment by asjr4584** [comment]
@lyn2711 I'm assigning this to you further testing. @chrisperez this must be treated as Critical and must be fixed ASAP.

**Comment by chrisperez** [comment]
@lyn2711, please test in 201.

**Comment by asjr4584** [comment]
@lyn2711 please test this today.

**Comment by lyn2711** [comment]
connected with Issue #76

**Comment by chrisperez** [comment]
@lyn2711 please explain how it is connected to #76.
